# fly.toml app configuration file generated for customer-manager on 2023-06-01T23:32:46+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "customer-manager"
primary_region = "waw"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]
  dockerfile = "./docker/Dockerfile"

[deploy]
  release_command = "customer-manager-migrations"

[http_service]
  internal_port = 8080
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
