# fly.toml app configuration file generated for customer-manager-api on 2023-06-02T08:58:33+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "customer-manager-api"
primary_region = "waw"

[build]
  dockerfile = "./docker/Dockerfile"

[deploy]
  release_command = "customer-manager-migrations"


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
