app = "customer-manager"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  dockerfile = "./docker/Dockerfile"

[experimental]
  auto_rollback = true

[deploy]
  release_command = "customer-manager-migrations"

[http_service]
  internal_port = 8080
  force_https = false
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

