app = "customer-manager-api"
primary_region = "waw"

[build]
  dockerfile = "./docker/Dockerfile"

[deploy]
  release_command = "customer-manager-migrations"


[http_service]
  # internal_port = 8080
  # force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
