version: "3"
services:
  customer-manager:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    env_file:
      - ../.env
    volumes:
      - ../:/home/appuser/app:rw
    depends_on:
      database:
        condition: service_healthy
      customer-manager-migrations:
        condition: service_completed_successfully

  proxy:
    build:
      context: traefik/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "80:80"

  customer-manager-migrations:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    env_file:
      - ../.env
    command: customer-manager-migrations
    depends_on:
      database:
        condition: service_healthy

  database:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: customer-manager
      MYSQL_PASSWORD: secret123
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: secret123
    healthcheck:
      test: ["CMD", "curl", "-f", "http://database:3306"]
      interval: 20s 
      timeout: 10s 
      retries: 3 
      start_period: 5s
