# fly.toml file generated for customer-manager on 2023-05-12T11:29:30+02:00

app = "customer-manager"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  dockerfile = "../docker/Dockerfile"

[experimental]
  auto_rollback = true

[deploy]
  release_command = "customer-manager-migrations"


