definitions:
  database.Customer:
    properties:
      created_at:
        type: string
      first_name:
        type: string
      id:
        type: string
      last_name:
        type: string
      telephone_number:
        type: string
      updated_at:
        type: string
    required:
    - first_name
    - last_name
    - telephone_number
    type: object
  database.Purchase:
    properties:
      created_at:
        type: string
      customer_id:
        type: string
      frame_model:
        type: string
      id:
        type: string
      lens_power:
        type: string
      lens_type:
        type: string
      pd:
        type: string
      purchase_type:
        type: string
      purchased_at:
        type: string
      updated_at:
        type: string
    type: object
  database.Repair:
    properties:
      cost:
        type: number
      created_at:
        type: string
      customer_id:
        type: string
      description:
        type: string
      id:
        type: string
      reported_at:
        type: string
    type: object
  server.CreateCustomerRequest:
    properties:
      first_name:
        type: string
      last_name:
        type: string
      telephone_number:
        type: string
    required:
    - first_name
    - last_name
    - telephone_number
    type: object
  server.CreatePurchaseRequest:
    properties:
      frame_model:
        type: string
      lens_power:
        type: string
      lens_type:
        type: string
      pd:
        type: string
      purchase_type:
        type: string
      purchased_at:
        description: TODO - when invalid date specified it returns field is required
        type: string
    required:
    - frame_model
    - lens_power
    - lens_type
    - pd
    - purchase_type
    - purchased_at
    type: object
  server.CreateRepairRequest:
    properties:
      cost:
        type: string
      description:
        type: string
      reported_at:
        type: string
    required:
    - cost
    - description
    - reported_at
    type: object
  server.EditCustomerDetailsRequest:
    properties:
      first_name:
        type: string
      last_name:
        type: string
      telephone_number:
        type: string
    required:
    - first_name
    - last_name
    - telephone_number
    type: object
  server.EditPurchaseRequest:
    properties:
      frame_model:
        type: string
      lens_power:
        type: string
      lens_type:
        type: string
      pd:
        type: string
      purchase_type:
        type: string
      purchased_at:
        description: TODO - when invalid date specified it returns field is required
        type: string
    required:
    - frame_model
    - lens_power
    - lens_type
    - pd
    - purchase_type
    - purchased_at
    type: object
info:
  contact: {}
paths:
  /api/customers:
    get:
      description: Returns full list of existing customers
      parameters:
      - description: first name search
        in: query
        name: firstName
        type: string
      - description: last name search
        in: query
        name: lastName
        type: string
      - default: 10
        description: list length
        in: query
        name: limit
        type: integer
      - default: 0
        description: list offset
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/database.Customer'
            type: array
      summary: Get list of customers
      tags:
      - list-customers
    post:
      consumes:
      - application/json
      description: Create customer object
      parameters:
      - description: Customer details
        in: body
        name: customerDetails
        required: true
        schema:
          $ref: '#/definitions/server.CreateCustomerRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/database.Customer'
        "400":
          description: IMPLEMENTED BUT DOCS TODO
          schema:
            type: string
      summary: Create customer
      tags:
      - create-customer
  /api/customers/{customerID}:
    delete:
      description: Delete customer details and it's relations by ID
      parameters:
      - description: Customer ID
        in: path
        name: customerID
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "400":
          description: IMPLEMENTED BUT DOCS TODO
          schema:
            type: string
        "404":
          description: IMPLEMENTED BUT DOCS TODO
          schema:
            type: string
      summary: Delete customer
      tags:
      - delete-customer
    get:
      description: Returns customer details by ID
      parameters:
      - description: Customer ID
        in: path
        name: customerID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/database.Customer'
        "400":
          description: IMPLEMENTED BUT DOCS TODO
          schema:
            type: string
        "404":
          description: IMPLEMENTED BUT DOCS TODO
          schema:
            type: string
      summary: Get customer
      tags:
      - get-customer
    put:
      description: Edit customer details by ID
      parameters:
      - description: Customer ID
        in: path
        name: customerID
        required: true
        type: string
      - description: New customer details
        in: body
        name: customerDetails
        required: true
        schema:
          $ref: '#/definitions/server.EditCustomerDetailsRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/database.Customer'
        "400":
          description: IMPLEMENTED BUT DOCS TODO
          schema:
            type: string
        "404":
          description: IMPLEMENTED BUT DOCS TODO
          schema:
            type: string
      summary: Edit customer
      tags:
      - edit-customer
  /api/customers/{customerID}/purchases:
    get:
      description: Returns full list of purchases for a specific customer by ID
      parameters:
      - description: Customer ID
        in: path
        name: customerID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/database.Purchase'
            type: array
      summary: Get list of purchases
      tags:
      - get-customer-purchases
    post:
      consumes:
      - application/json
      description: Creates a new purchase for a customer by ID
      parameters:
      - description: Customer ID
        in: path
        name: customerID
        required: true
        type: string
      - description: Purchase details
        in: body
        name: purchaseDetails
        required: true
        schema:
          $ref: '#/definitions/server.CreatePurchaseRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/database.Purchase'
        "400":
          description: IMPLEMENTED BUT DOCS TODO
          schema:
            type: string
        "404":
          description: IMPLEMENTED BUT DOCS TODO
          schema:
            type: string
      summary: Create a purchase for a customer
      tags:
      - create-customer-purchase
  /api/customers/{customerID}/purchases/{purchaseID}:
    delete:
      description: Deletes a purchase by ID
      parameters:
      - description: Customer ID
        in: path
        name: customerID
        required: true
        type: string
      - description: Purchase ID
        in: path
        name: purchaseID
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "400":
          description: IMPLEMENTED BUT DOCS TODO
          schema:
            type: string
        "404":
          description: IMPLEMENTED BUT DOCS TODO
          schema:
            type: string
      summary: Delete a purchase
      tags:
      - delete-customer-purchase
    put:
      description: Updates a purchase for a customer by ID
      parameters:
      - description: Customer ID
        in: path
        name: customerID
        required: true
        type: string
      - description: Purchase ID
        in: path
        name: purchaseID
        required: true
        type: string
      - description: New purchase details
        in: body
        name: customerDetails
        required: true
        schema:
          $ref: '#/definitions/server.EditPurchaseRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/database.Purchase'
        "400":
          description: IMPLEMENTED BUT DOCS TODO
          schema:
            type: string
        "404":
          description: IMPLEMENTED BUT DOCS TODO
          schema:
            type: string
      summary: Update a purchase
      tags:
      - update-customer-purchase
  /api/customers/{customerID}/repairs:
    get:
      description: Returns full list of repairs for a specific customer by ID
      parameters:
      - description: Customer ID
        in: path
        name: customerID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/database.Repair'
            type: array
      summary: Get list of repairs
      tags:
      - get-customer-repairs
    post:
      consumes:
      - application/json
      description: Creates a new repair for a customer by ID
      parameters:
      - description: Customer ID
        in: path
        name: customerID
        required: true
        type: string
      - description: Repair details
        in: body
        name: repairDetails
        required: true
        schema:
          $ref: '#/definitions/server.CreateRepairRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/database.Repair'
        "400":
          description: IMPLEMENTED BUT DOCS TODO
          schema:
            type: string
        "404":
          description: IMPLEMENTED BUT DOCS TODO
          schema:
            type: string
      summary: Create a repair for a customer
      tags:
      - create-customer-repair
  /api/customers/{customerID}/repairs/{repairID}:
    delete:
      description: Deletes a repair by ID
      parameters:
      - description: Customer ID
        in: path
        name: customerID
        required: true
        type: string
      - description: Repair ID
        in: path
        name: repairID
        required: true
        type: string
      responses:
        "204":
          description: No Content
        "400":
          description: IMPLEMENTED BUT DOCS TODO
          schema:
            type: string
        "404":
          description: IMPLEMENTED BUT DOCS TODO
          schema:
            type: string
      summary: Delete a repair
      tags:
      - delete-customer-repair
swagger: "2.0"
