
http:
  services:
    customer-manager:
      loadBalancer:
        servers:
        - url: "http://customer-manager:8080/"
    customer-manager-ui:
      loadBalancer:
        servers:
        - url: "http://customer-manager-ui:3000"
  routers:
    frontend:
      rule: "Path(`/`)"
      entrypoints:
        - web
      service: customer-manager-ui
    backend:
      rule: "PathPrefix(`/api`)"
      entrypoints:
        - web
      service: customer-manager

