
http:
  services:
    customer-manager:
      loadBalancer:
        servers:
        - url: "http://customer-manager-api.internal:8080"
    customer-manager-ui:
      loadBalancer:
        servers:
        - url: "http://customer-manager-ui.internal:3000"
  routers:
    frontend:
      rule: "PathPrefix(`/`)"
      entrypoints:
        - web
      service: customer-manager-ui
    backend:
      rule: "PathPrefix(`/api`)"
      entrypoints:
        - web
      service: customer-manager

