# fly.toml app configuration file generated for customer-manager-proxy on 2023-06-01T22:40:27+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "customer-manager-proxy"
primary_region = "waw"

[http_service]
  internal_port = 80
  force_https = false
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
