name: Run Tests
on: [push, pull_request]
jobs:
  test:
    name: Run Service Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout current repo
      - uses: actions/setup-go@v3
        name: Install Go
        with:
          go-version: '1.19.1'
      - name: Run database migrations
        run: go run ./cmd/migrate/migrate.go
      - name: Run tests
        run: go test -v ./...